# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Aaron
tagline:          'Aaron Test Blog'
description:      'Hi. I\'m Aaron. Here\'s some information about me.'
url:              http://aaronshim.github.io
baseurl:          /

author:
  name:           'Aaron Shim'
  url:            https://github.com/aaronshim

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
