# Site settings
title: Hi. I'm Aaron.
description: Coding & Other Things
url: 'https://shim.space'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: Aaron Shim
  email: aaron.k.shim@gmail.com
  github_username:  aaronshim
  linkedin_username: aaron-shim-41a46221
  resume: files/aaron_shim_resume.pdf

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
