# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Aaron Shim
tagline:          ''
description:      "Hi. I'm Aaron. You can reach me at aaron [dot] shim [at] yale [dot] edu"
url:              http://aaronshim.github.io
baseurl:          /

author:
  name:           'Aaron Shim'
  url:            https://github.com/aaronshim

paginate:         5
#destination: _site/blog
paginate_path: "blog/page:num/"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
