name: CI

on:
  pull_request:
  push:
    branches:
      - main # Ensure this is your default branch for deployments

# Grant permissions for the GITHUB_TOKEN
# This is required for actions/deploy-pages and the SLSA attestation action
permissions:
  contents: read # Allow checkout
  pages: write # Allow writing to the gh-pages branch (for deployment)
  id-token: write # Required for the actions/deploy-pages and SLSA attestation action

jobs:
  build-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            allow-import-from-derivation = true
            auto-optimise-store = true
            experimental-features = nix-command flakes
            substituters = https://cache.nixos.org https://cache.iog.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

      - name: Build with cachix
        uses: cachix/cachix-action@v16
        with:
          name: hakyll-nix-template
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      # Build your Hakyll site
      # Make sure this command outputs the static site to a known directory,
      # like ./result/dist based on your current setup.
      - run: nix build --accept-flake-config

      # --- NEW STEP: Generate SLSA Attestation ---
      # This action should run after the build step that produces the artifact.
      # It captures information about the build process and outputs an attestation.
      # Using the correct action name and a known version (v0.1.0 is a common starting point)
      - name: Generate SLSA Attestation
        uses: slsa-framework/slsa-github-generated-build@v0.1.0
        with:
          # The artifact-path should point to the directory containing the build output.
          # This helps link the attestation to the specific files produced.
          # The action will automatically detect the artifact if uploaded next.
          artifact-path: ./result/dist
          # You can specify other options here if needed,
          # but artifact-path is usually sufficient for basic attestation.

      # --- EXISTING STEP: Upload the built site as a pages artifact ---
      # This action uploads the build output directory for GitHub Pages deployment.
      # The SLSA action above will generate an attestation covering the creation
      # of the contents in this directory.
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./result/dist

  # --- MODIFIED JOB ---
  deploy:
    # Deploy only on pushes to the main branch
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [build-nix] # Depends on the build job completing successfully

    steps:
      # --- REMOVED STEP: Download artifact is not needed with actions/deploy-pages ---

      # --- MODIFIED STEP ---
      # Deploy the uploaded artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        # No 'with' or 'env' needed when using actions/upload-pages-artifact
