name: Codespaces Prebuild

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  prebuild:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prebuild
        uses: devcontainers/ci@v0.3
        with:
          image-name: ghcr.io/${{ github.repository }}/devcontainer
          push: always
          cache-from: ghcr.io/${{ github.repository }}/devcontainer
          token: ${{ secrets.GITHUB_TOKEN }}
